---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: docker
    directory: /IDE/.devcontainer
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: docker
    directory: /cloud-tool
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: docker
    directory: /CI/Dockerfiles
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: docker
    directory: /.clusterfuzzlite
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"
