---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: devcontainers
    directory: /IDE
    schedule:
      interval: "weekly"
      day: "saturday"

  # ********** Docker **********
  # Ubuntu
  - package-ecosystem: docker
    directories:
      - /CI/Dockerfiles
      - /cloud-tool
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      ubuntu:
        patterns:
          - "ubuntu*"

  # If it's not Ubuntu
  - package-ecosystem: docker
    directory: /CI/Dockerfiles
    schedule:
      interval: "weekly"
      day: "saturday"

  # nvidia/cuda
  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: "weekly"
      day: "saturday"

  # vscode/devcontainers/base
  - package-ecosystem: docker
    directory: /IDE/.devcontainer
    schedule:
      interval: "weekly"
      day: "saturday"

  # oss-fuzz-base/base-builder
  - package-ecosystem: docker
    directory: /.clusterfuzzlite
    schedule:
      interval: "weekly"
      day: "saturday"
