###############################################################################
#        _       _             _   _            _____  _
#       | |     | |           | | | |          |  __ \(_)
#       | | ___ | |__  _ __   | |_| |__   ___  | |__) |_ _ __  _ __   ___ _ __
#   _   | |/ _ \| '_ \| '_ \  | __| '_ \ / _ \ |  _  /| | '_ \| '_ \ / _ \ '__|
#  | |__| | (_) | | | | | | | | |_| | | |  __/ | | \ \| | |_) | |_) |  __/ |
#   \____/ \___/|_| |_|_| |_|  \__|_| |_|\___| |_|  \_\_| .__/| .__/ \___|_|
#                                                       | |   | |
#                                                       |_|   |_|
#
# Copyright (c) 2024 Claudio André <dev@claudioandre.slmail.me>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
###############################################################################
# GitHub Action to automatically merge PRs
# More info at https://github.com/openwall/john-packages

---
name: Merge bot

"on":
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: merge-dependabot

    permissions:
      contents: write
      pull-requests: write

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Auto-merge Dependabot PRs
        run: |
          gh pr checkout "$PR_URL"

          DATA="$(gh pr status --json latestReviews --jq '.currentBranch.latestReviews[].state == "APPROVED"')"
          APPROVALS="$(echo "$DATA" | grep -c 'true' || true)"
          echo "Approvals: $APPROVALS"

          if [[ "$APPROVALS" -ge 2 ]]; then
            echo "Auto-merge Dependabot PRs."
            gh pr merge --auto --squash "$PR_URL"
          else
            echo "Nothing to do."
          fi

        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
