######################################################################
# Copyright (c) 2021 Claudio André <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
######################################################################
name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Is it a release build (needs a git checkout)?'
        required: true
        default: 'false'
      hash:
        description: 'The commit hash to be used'
        required: false
        default: 'a16c8a76259ab870c07e5123c237b1900402d9a6'

env:
  REPO: ghcr.io/${{ github.repository_owner }}/john

jobs:
  push_to_registry:
    name: Push Docker image to a registry
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ../../Dockerfile
          build-args: |
            release=${{ github.event.inputs.release }}
            commit=${{ github.event.inputs.hash }}
          tags: |
            ${{ env.REPO }}:latest
            ${{ env.REPO }}:latest_J${{ github.run_number }}